/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWorkflowsRouteImport } from './routes/dashboard.workflows'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardRulesRouteImport } from './routes/dashboard.rules'
import { Route as DashboardRolesRouteImport } from './routes/dashboard.roles'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardMenusRouteImport } from './routes/dashboard.menus'
import { Route as DashboardFeaturesRouteImport } from './routes/dashboard.features'
import { Route as DashboardCompaniesRouteImport } from './routes/dashboard.companies'
import { Route as DashboardCatalogRouteImport } from './routes/dashboard.catalog'
import { Route as DashboardOrdersIdRouteImport } from './routes/dashboard.orders.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkflowsRoute = DashboardWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRulesRoute = DashboardRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenusRoute = DashboardMenusRouteImport.update({
  id: '/menus',
  path: '/menus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeaturesRoute = DashboardFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompaniesRoute = DashboardCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCatalogRoute = DashboardCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIdRoute = DashboardOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/menus': typeof DashboardMenusRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/menus': typeof DashboardMenusRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/companies': typeof DashboardCompaniesRoute
  '/dashboard/features': typeof DashboardFeaturesRoute
  '/dashboard/menus': typeof DashboardMenusRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/workflows': typeof DashboardWorkflowsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/catalog'
    | '/dashboard/companies'
    | '/dashboard/features'
    | '/dashboard/menus'
    | '/dashboard/orders'
    | '/dashboard/roles'
    | '/dashboard/rules'
    | '/dashboard/users'
    | '/dashboard/workflows'
    | '/dashboard/'
    | '/dashboard/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/catalog'
    | '/dashboard/companies'
    | '/dashboard/features'
    | '/dashboard/menus'
    | '/dashboard/orders'
    | '/dashboard/roles'
    | '/dashboard/rules'
    | '/dashboard/users'
    | '/dashboard/workflows'
    | '/dashboard'
    | '/dashboard/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/catalog'
    | '/dashboard/companies'
    | '/dashboard/features'
    | '/dashboard/menus'
    | '/dashboard/orders'
    | '/dashboard/roles'
    | '/dashboard/rules'
    | '/dashboard/users'
    | '/dashboard/workflows'
    | '/dashboard/'
    | '/dashboard/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows': {
      id: '/dashboard/workflows'
      path: '/workflows'
      fullPath: '/dashboard/workflows'
      preLoaderRoute: typeof DashboardWorkflowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rules': {
      id: '/dashboard/rules'
      path: '/rules'
      fullPath: '/dashboard/rules'
      preLoaderRoute: typeof DashboardRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menus': {
      id: '/dashboard/menus'
      path: '/menus'
      fullPath: '/dashboard/menus'
      preLoaderRoute: typeof DashboardMenusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/features': {
      id: '/dashboard/features'
      path: '/features'
      fullPath: '/dashboard/features'
      preLoaderRoute: typeof DashboardFeaturesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/companies': {
      id: '/dashboard/companies'
      path: '/companies'
      fullPath: '/dashboard/companies'
      preLoaderRoute: typeof DashboardCompaniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/catalog': {
      id: '/dashboard/catalog'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/$id': {
      id: '/dashboard/orders/$id'
      path: '/$id'
      fullPath: '/dashboard/orders/$id'
      preLoaderRoute: typeof DashboardOrdersIdRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
  }
}

interface DashboardOrdersRouteChildren {
  DashboardOrdersIdRoute: typeof DashboardOrdersIdRoute
}

const DashboardOrdersRouteChildren: DashboardOrdersRouteChildren = {
  DashboardOrdersIdRoute: DashboardOrdersIdRoute,
}

const DashboardOrdersRouteWithChildren = DashboardOrdersRoute._addFileChildren(
  DashboardOrdersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCatalogRoute: typeof DashboardCatalogRoute
  DashboardCompaniesRoute: typeof DashboardCompaniesRoute
  DashboardFeaturesRoute: typeof DashboardFeaturesRoute
  DashboardMenusRoute: typeof DashboardMenusRoute
  DashboardOrdersRoute: typeof DashboardOrdersRouteWithChildren
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardRulesRoute: typeof DashboardRulesRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardWorkflowsRoute: typeof DashboardWorkflowsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCatalogRoute: DashboardCatalogRoute,
  DashboardCompaniesRoute: DashboardCompaniesRoute,
  DashboardFeaturesRoute: DashboardFeaturesRoute,
  DashboardMenusRoute: DashboardMenusRoute,
  DashboardOrdersRoute: DashboardOrdersRouteWithChildren,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardRulesRoute: DashboardRulesRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardWorkflowsRoute: DashboardWorkflowsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
